### ISSUE TITLE
maven install is failing

### ISSUE THREAD

**Issue by RaniRaven** [devopvoid/webrtc-java#40]
It is unclear from the Readme what is needed for the maven install.
If I wish to build it on windows, do I need only visual studio build tools and it will work ?
Cause currently I am getting a lot of errors, some indicating that the branch has not been downloaded.
Is there anyway to get the binaries for the webrtc (windows) and save this 12GB download ?

Regards,
Rani

**Comment by devopvoid** [comment]
It depends on what you are planing to do:
* If you simply want to use the library for your own project, then add the Maven dependency shown in the readme to your project.
* You want to extend the native library or want to play around with the demo, then you need to build the whole project.

If you click on the [Visual Studio](https://chromium.googlesource.com/chromium/src/+/refs/heads/main/docs/windows_build_instructions.md#visual-studio) link in the readme, you get an instruction on all tools you need to install with/for Visual Studio.

It's actually a good point to provide the build WebRTC libraries, so you do not need to load and build it again and again. But it is a bad practice to distribute native libraries. It's an trust/security issue, since the provided library can contain malicious code.

Still, if you build the project once, you won't need to compile the WebRTC library again.

**Comment by RaniRaven** [comment]
o.k. thanx for the explanation.
